import bcrypt from "bcryptjs";

const data = {
    users: [
        {
            name: "Alice",
            email: "alice@example.com",
            password: bcrypt.hashSync("password"),
            isAdmin: true,
        },
        {
            name: "Bob",
            email: "bob@example.com",
            password: bcrypt.hashSync("password"),
            isAdmin: false,
        },
    ],

    products: [
        {
            name: "Manchester United home jersey 22-23",
            slug: "manchester-united-home-jersey-22-23",
            team: "manchester-united",
            category: "home",
            image: "/images/manu-home-22-23.jpg",
            price: 25000,
            rating: 5,
            numReviews: 26,
            countInStock: 70,
        },
        {
            name: "Manchester United away jersey 22-23",
            slug: "manchester-united-away-jersey-22-23",
            team: "manchester-united",
            category: "away",
            image: "/images/manu-away-22-23.jpg",
            price: 20000,
            rating: 4.5,
            numReviews: 10,
            countInStock: 30,
        },
        {
            name: "Arsenal home jersey 22-23",
            slug: "arsenal-home-jersey-22-23",
            team: "arsenal",
            category: "home",
            image: "/images/arsenal-home-22-23.jpg",
            price: 25000,
            rating: 4.3,
            numReviews: 20,
            countInStock: 50,
        },
        {
            name: "Arsenal away jersey 22-23",
            slug: "arsenal-away-jersey-22-23",
            team: "arsenal",
            category: "away",
            image: "/images/arsenal-away-22-23.jpg",
            price: 20000,
            rating: 4,
            numReviews: 13,
            countInStock: 20,
        },

        {
            name: "Manchester City home jersey 22-23",
            slug: "manchester-city-home-jersey-22-23",
            team: "manchester-city",
            category: "home",
            image: "/images/mancity-home-22-23.jpg",
            price: 25000,
            rating: 4.4,
            numReviews: 14,
            countInStock: 40,
        },
        {
            name: "Manchester City away jersey 22-23",
            slug: "manchester-city-away-jersey-22-23",
            team: "manchester-city",
            category: "away",
            image: "/images/mancity-away-22-23.jpg",
            price: 20000,
            rating: 3.5,
            numReviews: 10,
            countInStock: 30,
        },
        {
            name: "Chelsea home jersey 22-23",
            slug: "chelsea-home-jersey-22-23",
            team: "chelsea",
            category: "home",
            image: "/images/chelsea-home-22-23.jpg",
            price: 25000,
            rating: 4,
            numReviews: 10,
            countInStock: 50,
        },
        {
            name: "Chelsea away jersey 22-23",
            slug: "chelsea-away-jersey-22-23",
            team: "chelsea",
            category: "away",
            image: "/images/chelsea-away-22-23.jpg",
            price: 20000,
            rating: 4.2,
            numReviews: 8,
            countInStock: 20,
        },
        {
            name: "Liverpool home jersey 22-23",
            slug: "liverpool-home-jersey-22-23",
            team: "liverpool",
            category: "home",
            image: "/images/liverpool-home-22-23.jpg",
            price: 25000,
            rating: 4.6,
            numReviews: 18,
            countInStock: 60,
        },
        {
            name: "Liverpool away jersey 22-23",
            slug: "liverpool-away-jersey-22-23",
            team: "liverpool",
            category: "away",
            image: "/images/liverpool-away-22-23.jpg",
            price: 20000,
            rating: 4.1,
            numReviews: 12,
            countInStock: 25,
        },
        {
            name: "Spurs home jersey 22-23",
            slug: "spurs-home-jersey-22-23",
            team: "spurs",
            category: "home",
            image: "/images/spurs-home-22-23.jpg",
            price: 25000,
            rating: 4,
            numReviews: 9,
            countInStock: 40,
        },
        {
            name: "Spurs away jersey 22-23",
            slug: "spurs-away-jersey-22-23",
            team: "spurs",
            category: "away",
            image: "/images/spurs-away-22-23.jpg",
            price: 20000,
            rating: 3.6,
            numReviews: 10,
            countInStock: 20,
        },
        {
            name: "Real Madrid home jersey 22-23",
            slug: "real-madrid-home-jersey-22-23",
            team: "real-madrid",
            category: "home",
            image: "/images/real-madrid-home-22-23.jpg",
            price: 25000,
            rating: 4.9,
            numReviews: 22,
            countInStock: 50,
        },
        {
            name: "Real Madrid away jersey 22-23",
            slug: "real-madrid-away-jersey-22-23",
            team: "real-madrid",
            category: "away",
            image: "/images/real-madrid-away-22-23.jpg",
            price: 20000,
            rating: 4.2,
            numReviews: 13,
            countInStock: 35,
        },
        {
            name: "Barcelona home jersey 22-23",
            slug: "barcelona-home-jersey-22-23",
            team: "barcelona",
            category: "home",
            image: "/images/barcelona-home-22-23.jpg",
            price: 25000,
            rating: 4.6,
            numReviews: 21,
            countInStock: 50,
        },
        {
            name: "Barcelona away jersey 22-23",
            slug: "barcelona-away-jersey-22-23",
            team: "barcelona",
            category: "away",
            image: "/images/barcelona-away-22-23.jpg",
            price: 20000,
            rating: 4,
            numReviews: 16,
            countInStock: 20,
        },
    ],
};

export default data;
